### ISSUE TITLE
[게시판] 게시판 관련 UI 수정

### ISSUE THREAD

**Issue by dmdgpdi** [WeGrus/WeGrus-FE-React#111]
## Feature Description

- 추천 태그 UI 수정 => 추천 안한 상태에서는 보더만 색있고 추천 된 상태에서는 안까지 꽉차게 변경.
- 텍스트 댓글을 사용자 이름 선까지 내리기
- 공지사항이나, 소모임, 스터디의 경우에도 비밀글 적용하기 여부 적용.
- 공지사항은 배경색 회색빛 돌게해서 강조.
- 마우스 오버 시 회색 및 밑줄

## Todo list

- [x] 추천 태그 UI 수정 => 추천 안한 상태에서는 보더만 색있고 추천 된 상태에서는 안까지 꽉차게 변경.
- [x] 텍스트 댓글을 사용자 이름 선까지 내리기
- [x] 공지사항이나, 소모임, 스터디의 경우에도 비밀글 적용하기 여부 적용.
- [x] 공지사항은 배경색 회색빛 돌게해서 강조.
- [x] 마우스 오버 시 회색 및 밑줄
