### ISSUE TITLE
커뮤니티, 스터디, 공지사항 관련해서 수정할 사항 

### ISSUE THREAD

**Issue by dmdgpdi** [WeGrus/WeGrus-FE-React#46]
## Feature Description

- 디자인이나 로직적으로 수정해야할 사항을 적겠습니다. 수정해야할 부분이 생기신다면 이곳에 코멘트를 남겨주세요.
- description 2

## Todo list

- [x] 댓글과 대댓글에서 로그인한 유저의 이미지가 아니라 api에 담긴 이미지로 수정
- [x] 대댓글, 댓글 추천 여부를 확인하고 추천의 색이 바뀌는 것,
- [x] 추천버튼을 제외하고서 엄지를 눌러도 추천이 되게 로직 수정
