### ISSUE TITLE
[마이페이지] 프로필 수정

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-FE-React#67]
## Feature Description

- 마이페이지에 들어오자 마자, 프로필 수정 버튼을 누르면 (학과, 학년, 상태)가 초기값으로 설정되는데, 기존 값으로 설정되도록 바꾸면 좋을 것 같습니다.
    - 학과만 바꾸려는 사람이 학년과 상태까지 다시 설정해야하는 번거로움이 존재합니다.
    - ![image](https://user-images.githubusercontent.com/68049320/154809945-3e07083d-9326-4ec7-a2d4-0336d051f306.png)
- 다음으로 수정을 누르면, 학년과 상태가 Enum 값으로 설정되어 보여집니다. 
    - api 응답으로는 한글 값으로 전달되는데, 이 부분 적용이 안 된 것 같습니다.
    - ![image](https://user-images.githubusercontent.com/68049320/154810082-63777e85-481b-469d-aaa1-e1ab5999bd30.png)
- 다음으로 새로고침을 누르면 about 화면으로 이동되는데, 페이지 이동 없이 마이페이지로 유지되도록 수정해주세요.
    - 이 때는 마이페이지에 학년과 상태가 한글로 표시됩니다.
    - ![image](https://user-images.githubusercontent.com/68049320/154810134-44008059-7194-4229-affd-b4b3d800c0aa.png)

## Todo list

- [ ] 프로필 수정 시, 초기값을 본인 정보로 유지
- [ ] 프로필 수정 직후, 학년과 상태를 한글값으로 표시
- [ ] 새로고침 시 현 페이지 유지 (페이지 이동 x)
