### ISSUE TITLE
[게시물 검색] 검색 타입 글씨 색 변경 등

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-FE-React#78]
## Feature Description

- 색이 회색이라 눈에 띄지 않습니다. 검은색이나 다른 진한 색으로 변경해주세요.
    - ![image](https://user-images.githubusercontent.com/68049320/154811227-1718cc62-cd2f-4f91-98b9-c33cea078f71.png)
- 검색 버튼에 돋보기 모양을 추가해주세요. 더 인식하는게 쉬울 것 같습니다. 그리고 placeholder 문구도 추가해주세요.
    - ![image](https://user-images.githubusercontent.com/68049320/154811296-e481083e-0971-4135-a6e7-aa9019e3818d.png)
    - 참고(에브리타임)
        - ![image](https://user-images.githubusercontent.com/68049320/154811328-32456773-e2aa-4310-bee6-4ef178659afc.png)
- 정렬 타입을 선택하는 영역에 테두리를 추가해주세요.
    - ![image](https://user-images.githubusercontent.com/68049320/154811803-a6a2424f-0f91-46cb-b093-1f50f65a43f8.png)

## Todo list

- [x] 검색 타입 글씨 색 변경
- [x] 검색 버튼 수정
- [x] 정렬 영역 테두리 추가
