### ISSUE TITLE
[게시물] 게시물 작성 시 리다이렉트 

### ISSUE THREAD

**Issue by dmdgpdi** [WeGrus/WeGrus-FE-React#88]
## Feature Description

- #85 의 의견에 동의해 작성 버튼 누를 때 alert는 없는 게 좋을 것 같고, 해당 게시물 페이지로 리다이렉트 시키는게 좋을 것 같습니다.
- 기존의 page는 게시판 목록에서 postId를 전달받아 페이지를 만들었습니다. 이를 url의 path값으로 전달해 api를 호출할 수 있게 변경 
   할 예정입니다.

## Todo list

- [x] postId를 전달하지 말고 path값으로 변경하기
- [x] 받은 path값으로 pageNew.js 수정
- [ ] 게시물 작성 버튼을 누를시 page로 리다이렉트
